version: '3.3'

services:
  mongo:
    image: mongo:4.4-bionic
    container_name: mongo_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./db-seed:/db-seed
      - ./datasets:/datasets

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_service
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production

volumes:
  dbdata:
  db-seed:
